apiVersion: v1
kind: Service
metadata:
  name: agones-gameserver
spec:
  type: LoadBalancer
  externalIPs: ["172.31.71.218"]
  selector:
    agones.dev/gameserver: game-server
  ports:
  - protocol: UDP
    port: 7000 # local port
    targetPort: 7654
